- name: install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: remove old content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Download and extract frontend content
  include_role:
    name: common
    tasks_from: download

- name: copy the extracted content
  copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html/
    remote_src: yes
  when: APP_VERSION is not defined

- name: Create App code  Dir
  file:
    path: /usr/share/nginx/html/
    state: directory
  when:  APP_VERSION is defined

#- name: Download and Extract content
#  ansible.builtin.unarchive:
#    src: http://172.31.12.56:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{APP_VERSION}}.zip
#    dest: /usr/share/nginx/html/
#    remote_src: yes
#  when: APP_VERSION is defined

- name: Download Artifacts
  shell: az artifacts universal download --organization "https://dev.azure.com/rahemmedeee/" --project "c538555b-82eb-4acf-8907-01f0a2a72e5d" --scope project --feed "batch57" --name {{COMPONENT}} --version {{APP_VERSION}} --path .
  args:
    chdir: /usr/share/nginx/html/
  when: APP_VERSION is defined

- name: Update main Nginx config
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf


#- name: Copy roboshop configuration file
#  copy:
#      src: roboshop.conf
#      dest: /etc/nginx/default.d/roboshop.conf

- name: Update roboshop configuration file
  template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf
  when: COMPONENT is not defined

## For updating 80 port
- name: Update roboshop configuration file for LB
  template:
    src: roboshop-lb.conf
    dest: /etc/nginx/default.d/roboshop.conf
  when: COMPONENT is defined

- name: Install node exporter
  include_role:
    name: common
    tasks_from: node-exporter.yml

- name: Setup Filebeat
  include_role:
    name: common
    tasks_from: filebeat
  vars:
    LOG_FILE: /var/log/nginx/access.log
    STRUCTURED: "false"
    APP_TYPE: nginx


- name: Restart Nginx Service
  systemd:
    name: nginx
    state: restarted
    enabled: yes
