- name: Demo on when conditions
  hosts: localhost
  vars:
    URL: google.org
    a: 10
    ACTION: false
  tasks:
    - name: Conditon on strings
      when: URL == "google.com"
      debug:
        msg: Hello string

    - name: Conditon on strings
      when: URL != "google.com"
      debug:
        msg: Hello string

    - name: Condition on number
      when: a == 10
      debug:
        msg: Hello Number

    - name: Condition on number
      when: a <= 10
      debug:
        msg: Hello Number

    - name: Run if action is true
      when: ACTION
      debug:
        msg: Hello true

    - name: Run if action is not true
      when: not ACTION
      debug:
        msg: Hello false