- name: Demo on when conditions
  hosts: localhost
  vars:
    URL: google.org
    a: 10
  tasks:
    - name: Conditon on strings
      when: URL == "google.com"
      debug:
        msg: Hello string

    - name: Conditon on strings
      when: URL != "google.com"
      debug:
        msg: Hello string

    - name: Condition on number
      when: a == 10
      debug:
        msg: Hello Number

    - name: Condition on number
      when: a <= 10
      debug:
        msg: Hello Number