- name: Setup MySQL Repo file
  copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install MySQL Server
  yum:
    name: [ "mysql-community-server", "MySQL-python" ]
    state: present

- name: Start MySQL Service
  systemd:
    name: mysqld
    state: started
    enabled: yes

- name: Check the default password
  community.mysql.mysql_query:
    query: Show databases
    login_password: Roboshop@1
    login_user: root
  register: default_mysql_check
  ignore_errors: yes

#- name: Check the default password
#  shell: echo "Show databases;" | mysql -uroot -pRoboshop@1
#  register: default_mysql_check
#  ignore_errors: yes

- name: Grab default password
  when: default_mysql_check.failed
  shell: grep 'A temporary password' /var/log/mysqld.log | awk '{print $NF}'
  register: out

- name: Reset MYSQL password
  shell: echo "ALTER USER 'root'@'localhost' IDENTIFIED BY 'Roboshop@1';" | mysql --connect-expired-password -uroot -p{{out}}


