- name: Create App code  Dir
  file:
    path: /home/roboshop/{{COMPONENT}}
    state: directory
  become_user: roboshop


- name: Download and Extract content
  ansible.builtin.unarchive:
    src: http://172.31.12.56:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{APP_VERSION}}.zip
    dest: /home/roboshop/{{COMPONENT}}
    remote_src: yes
  become_user: roboshop
  when: COMPONENT != "frontend"

