- name: Add Roboshop Application User
  ansible.builtin.user:
    name: roboshop

- name: Download from github
  include_tasks:
    file: download-from-github.yml

- name: Delete old app code
  file:
    path: /home/roboshop/{{COMPONENT}}
    state: absent

- name: copy the extracted content
  copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}/
    remote_src: yes
    owner: roboshop
    group: roboshop