- name: Check node exporter does exist
  stat:
    path: /opt/node_exporter
  register: out

- name: debug
  debug:
    msg: "{{out}}"

- name: Download prometheus archive
  unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v1.2.2/node_exporter-1.2.2.linux-amd64.tar.gz"
    dest: /tmp
    remote_src: yes

