- name: Check node exporter does exist
  stat:
    path: /opt/node_exporter
  register: out

- name: debug
  debug:
    msg: "{{out}}"

- name: debug
  debug:
    msg: "{{NODE_EXPORTER_URL | split('/') | last }}"

#- name: Download prometheus archive
#  unarchive:
#    src:
#    dest: /tmp
#    remote_src: yes
#- name: Copy node exporter to /opt
#  copy:
#    src: /tmp/node_exporter-1.2.2.linux-amd64
#    dest: /opt/node-exporter
#    remote_src: yes
