- name: Check node exporter does exist
  stat:
    path: /opt/node_exporter
  register: out

#- name: debug
#  debug:
#    msg: "{{out}}"

- name: Install node Exporter
  when: not out.stat.exists
  block:
    - name: Download prometheus archive
      unarchive:
        src:
        dest: /tmp
        remote_src: yes
    - name: Copy node exporter to /opt
      copy:
        src: /tmp/{{NODE_EXPORTER_URL | split('/') | last | regex_replace('.tar.gz','') }}
        dest: /opt/node-exporter
        remote_src: yes
